engines:
  pep8:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-3"
    config:
      config: client/.eslintrc.js
    checks:
      import/no-unresolved:
        enabled: false
ratings:
  paths:
  - "redash/**/*.py"
  - "client/**/*.js"
exclude_paths:
- tests/**/*.py
- migrations/**/*.py
- old_migrations/**/*.py
- setup/**/*
- bin/**/*

